# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraEntradaFunci', models.DateTimeField(blank=True, null=True)),
                ('dataHoraSaidaFunci', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=20)),
                ('chefe', models.BooleanField(default=False, verbose_name='Chefe de Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeChefe', models.CharField(max_length=128)),
                ('dataHoraEntradaPonto', models.DateTimeField()),
                ('dataHoraSaidaPonto', models.DateTimeField()),
                ('tipo', models.CharField(max_length=20)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ipMaquina', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('justificativa', models.TextField()),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa_Ponto', to='frequencia.Funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='configuracao',
            name='cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa_Horario', to='frequencia.Funcionario'),
        ),
    ]
