# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='codigo',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
    ]
